OrganiWebUI/Models/ViewModel/HomeViewModel.cs
using Organi.Domain.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Organi.Domain.ViewModel
{
    public class HomeViewModel
    {
        public List<Category> Categories { get; set; }
        public List<Product> FeateredProducts { get; set; }
    }
}

OrganiWebUI/Areas/Admin/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Organi.Domain.DataContext;
using Organi.Domain.Entity;
using Organi.Domain.ViewModel;

namespace OrganiWebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactsController : Controller
    {
        private readonly OrganiDbContext _context;
        readonly IConfiguration conf;

        public ContactsController(OrganiDbContext context, IConfiguration conf)
        {
            this.conf = conf;
            _context = context;
        }

        // GET: Admin/Contacts
        [HttpGet]
        public IActionResult Index(
            int pageIndex = 1,
            int pageSize = 3)
        {

            /*if (typeId.HasValue && typeId == 1)
            {
                query = query.Where(c => c.Answer == null);
            }*/
            var query = _context.Contacts
                .OrderByDescending(c => c.Id);
            var model = new PagedViewModel(query, pageIndex, pageSize);

            return View(model);
        }

        // Post: Admin/Contacts/Answer/5
        public async Task<IActionResult> Answer(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }
            if(contact.Answer != null)
            {
                return BadRequest();
            }
            return View(contact);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Answer(int id,[Bind("Id,Answer ")]Contact contact)
        {
            try
            {
                if (id != contact.Id)
                {
                    return NotFound();
                }

                var entity = await _context.Contacts
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (entity == null)
                {
                    return NotFound();
                }
                if (entity.Answer != null)
                {
                    return NotFound();
                }

                entity.Answer = contact.Answer;
                entity.AnswerDate = DateTime.UtcNow.AddHours(4);

                var host = conf.GetSection("emailAccount").GetSection("server").Value;
                var port = int.Parse(conf.GetSection("emailAccount").GetSection("port").Value);
                var userName = conf.GetSection("emailAccount").GetSection("userName").Value;
                var password = conf.GetSection("emailAccount").GetSection("password").Value;
                //string[] cc = conf.GetSection("emailAccount").GetSection("cc").Value
                //    .Split(";",StringSplitOptions.RemoveEmptyEntries);
                SmtpClient client = new SmtpClient(host, port);
                client.Credentials = new NetworkCredential(userName, password);
                client.EnableSsl = true;
                MailMessage message = new MailMessage(userName, entity.Email, "Organi Admin", entity.Answer);
                message.IsBodyHtml = true;
                //foreach (var address in cc)
                //{
                //    message.CC.Add(address);
                //}
                client.Send(message);

                _context.Entry(entity).State = EntityState.Modified;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                throw new Exception("hey");
            }
            
        }
    }
}

OrganiWebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Organi.Domain.DataContext;
using Organi.Domain.Entity;
using Organi.Domain.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganiWebUI.Controllers
{
    public class HomeController : Controller
    {
        readonly OrganiDbContext db;
        public HomeController(OrganiDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            var model = new HomeViewModel();
            model.Categories = db.Categories.Where(c => c.IsFeatured == true).ToList();
            model.FeateredProducts = db.Products
                .Include(p => p.Category)//lazy loading
                .Include(p => p.Images)
               .Where(p => p.Category.IsFeatured == true).ToList();

            //evvelce model ve viewbagdan istifade etdik, sonra viewmodelden

            //var categories = db.Categories.Where(x => x.IsFeatured == true).ToList();
            //ViewBag.Products = db.Products.Include(p => p.Category)//lazy loading
            //    .Where(p => p.Category.IsFeatured == true).ToList();  
            return View(model);
        }

        public  IActionResult Contact()
        {
            ViewBag.AppInfo = db.AppInfos.FirstOrDefault();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Contact(Contact contact)
        {
            //tekrar yazmaq lazimdi, cunki viewbag bir request boyu aktiv olur
            ViewBag.AppInfo = db.AppInfos.FirstOrDefault();
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();

                ModelState.Clear();
                ViewBag.Message = "Sorgunuz qebul olundu";
                return View();
            }
            return View(contact);
        }

        public IActionResult Subscribe(string email)
        {
            if (string.IsNullOrWhiteSpace(email))
            {
                return Json(new
                {
                    error = true,
                    message = "Email doldurulmayib"
                });
            }
            else if (db.Subcribes.Any(s => s.Email == email)){
                return Json(new
                {
                    error = true,
                    message = "Artiq abune olmusunuz"
                });
            }
            else
            {
                var subcribe = new Subscribe
                {
                    Email = email
                };
                db.Subcribes.Add(subcribe);
                db.SaveChanges();

                return Json(new
                {
                    error = false,
                    message = "Abune oldunuz"
                });
            }
        }
    }
}

OrganiWebUI/appCode/Components/ProductByCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Organi.Domain.DataContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OrganiWebUI.appCode.Components
{
    public class ProductByCategoryViewComponent : ViewComponent
    {
        readonly OrganiDbContext db;
        public ProductByCategoryViewComponent(OrganiDbContext db)
        {
            this.db = db;   
        }

        public IViewComponentResult Invoke(string title)
        {
            //var query = db.Products.AsQueryable();
            var products = db.Products
                .Include(p => p.Images)
                .OrderByDescending(x => x.Id).Take(3).ToList();//--muxtelif sertlere gore bir nece query yazmaga imkan verir ve yekunda eyni productsi gondermek olur/
              //-- bu sekilde model gonderib view terfden qarsilamaq da mumkundur-- 
            ViewBag.CategoryTitle = title;
            return View(products);
        }
    }
}

OrganiWebUI/Views/Home/Contact.cshtml
@model Contact
@{ 
    ViewBag.Title = "Contact";
    var appInfo = ViewBag.AppInfo as AppInfo; 
}
<section class="breadcrumb-section set-bg" data-setbg="/assets/img/breadcrumb.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Contact Us</h2>
                    <div class="breadcrumb__option">
                        <a href="index-2.html">Home</a>
                        <span>Contact Us</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_phone"></span>
                    <h4>Phone</h4>
                    <p>@appInfo.Phone</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_pin_alt"></span>
                    <h4>Address</h4>
                    <p>@appInfo.Address</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_clock_alt"></span>
                    <h4>Open time</h4>
                    <p>@appInfo.OpenTime</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_mail_alt"></span>
                    <h4>Email</h4>
                    <p><a href="mailto:@appInfo.Email?subject=Organi%20Question&body=Mesaj">@appInfo.Email</a></p>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d49116.39176087041!2d-86.41867791216099!3d39.69977417971648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x886ca48c841038a1%3A0x70cfba96bf847f0!2sPlainfield%2C%20IN%2C%20USA!5e0!3m2!1sen!2sbd!4v1586106673811!5m2!1sen!2sbd" height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    <div class="map-inside">
        <i class="icon_pin"></i>
        <div class="inside-widget">
            <h4>New York</h4>
            <ul>
                <li>Phone: +12-345-6789</li>
                <li>Add: 16 Creek Ave. Farmingdale, NY</li>
            </ul>
        </div>
    </div>
</div>


<div class="contact-form spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="contact__form__title">
                    <h2>Leave Message</h2>
                </div>
            </div>
        </div>
        <form method="post">
            @if (!string.IsNullOrWhiteSpace(ViewBag.Message))
            {
                <div class="alert alert-danger">
                    @ViewBag.Message
                </div>            }

            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Your name" asp-for="Name">
                </div>
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Your email" asp-for="Email">
                </div>
                <div class="col-lg-12 text-center">
                    <textarea placeholder="Your message" asp-for="Message"></textarea>
                    <button type="submit" class="site-btn">SEND MESSAGE</button>
                </div>
            </div>
        </form>
    </div>
</div>

OrganiWebUI/Views/Home/Index.cshtml
 @model HomeViewModel
@{
    //var products = ViewBag.Products as List<Product>;
}

<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="/assets/img/categories/cat-1.jpg">
                        <h5><a href="#">Fresh Fruit</a></h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="/assets/img/categories/cat-2.jpg">
                        <h5><a href="#">Dried Fruit</a></h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="/assets/img/categories/cat-3.jpg">
                        <h5><a href="#">Vegetables</a></h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="/assets/img/categories/cat-4.jpg">
                        <h5><a href="#">drink fruits</a></h5>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="/assets/img/categories/cat-5.jpg">
                        <h5><a href="#">drink fruits</a></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                        @foreach (var category in Model.Categories)
                        {
                            <li data-filter=".@category.Name.Replace(" ", "-")">@category.Name</li>
                            @* data-filter de .class isaresin yaddan cixarmaq olmaz cunki filter class adina gore olur*@
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            @foreach (var product in Model.FeateredProducts)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 mix @product.Category.Name.Replace(" ", "-")">
                    <div class="featured__item">
                        <div class="featured__item__pic set-bg" data-setbg="/uploads/@product.Images.FirstOrDefault(i => i.IsMain==true).Path">
                            <ul class="featured__item__pic__hover">
                                <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                <li><a onclick="addToCard(@product.Id,event)"><i class="fa fa-shopping-cart"></i></a></li>
                            </ul>
                        </div>
                        <div class="featured__item__text">
                            <h6><a href="#">@product.Name</a></h6>
                            <h5>@product.Price</h5>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>


<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="~/assets/img/banner/banner-1.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="~/assets/img/banner/banner-2.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>


<section class="latest-product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                @await Component.InvokeAsync("ProductByCategory", new
                {
                title = "Latest Products"
                })
            </div>
            <div class="col-lg-4 col-md-6">
                @await Component.InvokeAsync("ProductByCategory", new
                {
                title = "Top Rated Products"
                })
            </div>
            <div class="col-lg-4 col-md-6">
                @await Component.InvokeAsync("ProductByCategory", new
                {
                title = "Review Products"
                })
            </div>
        </div>
    </div>
</section>


<section class="from-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title from-blog__title">
                    <h2>From The Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/assets/img/blog/blog-1.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Cooking tips make cooking simple</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/assets/img/blog/blog-2.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">6 ways to prepare breakfast for 30</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="~/assets/img/blog/blog-3.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Visit the clean farm in the US</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Banner{
    <div class="hero__item set-bg" data-setbg="/assets/img/hero/banner.jpg">
        <div class="hero__text">
            <span>FRUIT FRESH</span>
            <h2>Vegetable <br />100% Organic</h2>
            <p>Free Pickup and Delivery Available</p>
            <a href="#" class="primary-btn">SHOP NOW</a>
        </div>
    </div>

}

@section script{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script>
        $('div.hero__categories > ul').css({
            display: "block"
        });

        function onlyUnique(value, index, self) {
            return self.indexOf(value) === index;
        }

        function addToCard(id, event) {
            //console.log("helo");
            event.stopPropagation();
            event.preventDefault();

            let cardItems = $.cookie("card-item");
            let items;

            if (cardItems == null) {
                items = [];
            }
            else {
                items = cardItems.split(',').map(e => parseInt(e));
            }
            items.push(id);
            items = items.filter(onlyUnique);
            $.cookie("card-item", items.toString(), { expires: 365 });
            $('.item-count').removeClass('d-none').html(items.length);
        }
    </script>

}